### ISSUE TITLE
Default Solver arg in Model Testing

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit-models#102]
I had `solver='mosek'` as an argument to localsolve and for some reason it caused the mac Sierra cvxopt tests to fail because MOSEK couldn't be imported. I thought it was odd this only happened on mac and could be worth posting.

```
Could not load MOSEK library: ImportError(OSError('dlopen(/Users/jenkins/workspace/gpkit_ResearchModel_turbofan_Push/buildnode/macys_Sierra/optimizer/cvxopt/build_gpkit/expopt.so, 10): Library not loaded: libmosek64.8.0.dylib\n  Referenced from: /Users/jenkins/workspace/gpkit_ResearchModel_turbofan_Push/buildnode/macys_Sierra/optimizer/cvxopt/build_gpkit/expopt.so\n  Reason: image not found',),)
```

**Comment by bqpd** [comment]
Yeah, right now GPkit will try to find a solver that it's asked for, even if it's not in the list of installed solvers, so for testing it's best to just use no `solver=` arg and specify solvers to skip in the `skipsolvers` arg of `TESTCONFIG`
