### ISSUE TITLE
Use gnuplot instead of matplotlib?

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit-models#104]
@whoburg @bqpd as @mjburton11 and I discovered it'd be really nice to generate all our plots as .eps files. We mentioned using gnuplot to Ned and he said it had some advantages....Woody what do you think about all of us starting to switch over to gnuplot instead of matplotlib?

**Comment by whoburg** [comment]
works for me, I see that decision as beyond the gpkit and gpkit-models abstraction barrier.

**Comment by bqpd** [comment]
Yerp. re: use in current use-cases, though, I think having a separate gnuplot script that runs on output data
