### ISSUE TITLE
Air density as a function of elevation

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit-models#4]
This would lead to more-meaningful sensitivities for aircraft.

**Comment by bqpd** [comment]
Convex to 27.4km:

![image](https://cloud.githubusercontent.com/assets/1482776/10628698/e2974222-7795-11e5-97bf-3a965ad15667.png)

**Comment by pgkirsch** [comment]
wait i did this already!

**Comment by bqpd** [comment]
woot!

**Comment by bqpd** [comment]
And here I was looking forward to using gpfit :p

**Comment by pgkirsch** [comment]
https://github.mit.edu/convex/GPjet/blob/master/standard_atmosphere.py

**Comment by pgkirsch** [comment]
I tried using GPfit but it failed me for some reason and I haven't had time to figure out why

**Comment by bqpd** [comment]
I'll mess around a bit some other time, then :D

**Comment by whoburg** [comment]
wait that only goes to 15km, a bit higher would help my current application

also, a GP, not SP, model seems achievable from the plot above, assuming that the application is putting upward pressure on h and rho

**Comment by bqpd** [comment]
In such a model I'd be tempted to back gravity in as a EQ constraint just so it'd stop showing up in sensitivities :p

**Comment by pgkirsch** [comment]
Hmmm that was just my first take at a working solution, will look into it some more.

**Comment by whoburg** [comment]
great! awesome.

**Comment by pgkirsch** [comment]
Addressed in #45
