### ISSUE TITLE
gpkit models needs a setup script

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit-models#56]
Need a simple `setup.py` so that users can install the package and use it in other applications.

First, we need to decide what the package name is:
`gpkitmodels`?
`gpkm`?
`gpkmodels`?

We'll move all the models into a folder of that name.

**Comment by bqpd** [comment]
I favor `gpkitmodels`

**Comment by pgkirsch** [comment]
It seems this issue should have been closed by #61
