### ISSUE TITLE
how do I write test methods

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit-models#59]
What's the best practice for writing test methods for models in the model library? I'd like the general philosophy to be:

 - models don't have default values placed directly in the variables or constraints
 - test methods substitute some default values and choose a reasonable objective, and then solve

I don't want to use `.substitutions.update` in `test(self, ...)` because then calling test mutates the substitutions of the model, which is unexpected.

Should models also expose some sort of `defaults()` method that gives default substitutions?

Can we get an example of a simple model with a test method?

**Comment by bqpd** [comment]
How about test as a class method?

**Comment by bqpd** [comment]
example:

```python
class Atmosphere(ConstraintSet):
    #...
    @classmethod
    def test(cls):
        import numpy.testing as npt
        cs = cls()
        m = Model(cs["\\rho"], cs)
        sol = m.solve()
        # test the solution


Atmosphere.test()
```

**Comment by whoburg** [comment]
sounds good.

**Comment by pgkirsch** [comment]
@bqpd: @whoburg and I discussed using this same structure for making different variants on models 
e.g.
```
@classmethod
def standalone_737(cls):
     objective = ...
     substitutions = {...}
    m  = Model(....)
    return m

@classmethod
def aircraft_737(cls): # for full aircraft model
    substitutions = {....} # shorter substitutions dict
    m  = Model(....)
    return m
```

How do you feel about this? I'm currently in the middle of implementing it for my GPjet models as a test before porting over to gpkit models and (hopefully) ending GPjet for good.

**Comment by pgkirsch** [comment]
Where the original 
```python
class VerticalTail(Model):
...
```

becomes
```python
class VerticalTail(ConstraintSet):
...
```

**Comment by bqpd** [comment]
Ooh, I like that!

**Comment by pgkirsch** [comment]
Sweet. One thing I can't figure out: does this mean `ConstraintSet` will need a `__getitem__` method to be able to do something like `objective = cs['W_{vt}']`?

**Comment by bqpd** [comment]
Yeah, I'm going to rename constraintset to something else so it can have user-facing things like that.

**Comment by bqpd** [comment]
But for now you could just use strings.

**Comment by pgkirsch** [comment]
what do you mean use strings?

**Comment by pgkirsch** [comment]
One thing I have figure out is how to do it with CostedConstraintSet, which also works pretty well I think

**Comment by bqpd** [comment]
Oh, derp. I was thinking for substitutions. For cost there's no nice way to do it right now.

**Comment by bqpd** [comment]
Yeah, costedconstraintset has getitem
