### ISSUE TITLE
unit tests currently failing

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit-models#6]
- [x] define what a "model test" is and looks like. @bqpd says: "I think some of what we have in gpkit are candidate templates for this..."
- [x] write at least one actual unit test
- [ ] ask @galbramc for help setting up CI on this repo

**Comment by galbramc** [comment]
What is the purpose of this repo? What needs to be tested and how are the tests executed?

**Comment by whoburg** [comment]
It's a subrepo of gpkit -- it's the `models` dir here: https://github.com/convexopt/gpkit/tree/master/gpkit. We decided to split our modeling efforts from our under-the-hood code.

We currently have no tests for the models repo but we intend to create tests.

**Comment by whoburg** [comment]
The dependencies will be the same as gpkit; nothing additional.

**Comment by galbramc** [comment]
Ok. Let me know when you have testing and we will setup the CI. Should this be tested separate from the regular gpkit pull request and push CI jobs? Or should we just extend those scripts to include the tests of this subrep?

**Comment by whoburg** [comment]
good question! I think we'll need to think that over.

**Comment by whoburg** [comment]
@bqpd, wouldn't it be straightforward to define a set of default unit tests that simply runs the `test()` method of every model in the gpkit-models repo? I think this is becoming important.

**Comment by bqpd** [comment]
For sure!

**Comment by whoburg** [comment]
Let's get `testing.py` up and running so that we can fire up Jenkins on this repo.

**Comment by whoburg** [comment]
high priority!

**Comment by whoburg** [comment]
ping -- running `testing.py` currently results in an `ImportError` for me.

Having tests working on this repo is important because we currently have other repos that depend on this one! (and I'm seeing failures)

**Comment by bqpd** [comment]
testing.py is not used by any Jenkins unit tests at the moment.

**Comment by bqpd** [comment]
Yeah, it still references some non-existent models. `testing.py` is not a current concern and we should probably delete it; any future unittesting framework is likely to be based on the research-repo tests.
