### ISSUE TITLE
breguet range convergence problems

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit-models#76]
this is a reminder for @mayork to create the most simple breguet range possible with the formulation at commit 	2256aea so we can analyze it

**Comment by mayork** [comment]
done

**Comment by whoburg** [comment]
(Where can we see it?)

**Comment by mayork** [comment]
whoops didn't push anything. I will in a minute....also made the attached  write up

[Breguet_Range_Write_Up_draft.pdf](https://github.com/hoburg/gpkit-models/files/439256/Breguet_Range_Write_Up_draft.pdf)

**Comment by whoburg** [comment]
@mayork you might now want to update https://github.com/hoburg/gpkit-models/blob/master/gpkitmodels/aircraft/breguet_range.py accordingly in a PR

**Comment by bqpd** [comment]
Nice. How would we merge sweet model documentation like this into gpkit-models? pandoc can turn the latex into markdown / RsT / html...

**Comment by whoburg** [comment]
@bqpd, I would have asked you the same question (it's a recurring one)

**Comment by bqpd** [comment]
I was wondering if anyone else would suggest markdown. :p
