### ISSUE TITLE
Where is code for signomial equality paper?

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit-models#81]
where is the code for the UAV example in the signomial programming paper? I'm really struggling with an atmosphere model and would like to see the example. @mopg I'm guessing you would know this.

**Comment by mopg** [comment]
I'll add it to gpkit-models. Was actually trying to do this right now, but git is having some issues, I can't push to the branch. I'll post here once I figured it out.

**Comment by mopg** [comment]
@whoburg seems like I don't have push permission for gpkit-models? I created a new branch but it doesn't allow me to push it with `git push -u origin equality`. My username and everything is set up correctly.

In the mean time, I'll email you the scripts.

**Comment by mayork** [comment]
addressed by PR #83

**Comment by mayork** [comment]
it works, thanks!
